---
apiVersion: v1
kind: Namespace
metadata:
    name: oreore1
    labels:
        name: oreore-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oreore-deployment
spec:
  selector:
    matchLabels:
      app: oreore-app
  template:
    metadata:
      labels:
        app: oreore-app
    spec:
      containers:
        - name: hello-node
          image: "gcr.io/hello-minikube-zero-install/hello-node"
---
apiVersion: v1
kind: Service
metadata:
    name: oreore-service
spec:
    type: LoadBalancer
    ports:
        - protocol: "TCP"
          port: 8080
    selector:
        app: oreore-app

